#!/bin/bash
# Install/update/check vendorable Zephyr container infra in target repos.
set -eu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
SKILL_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
readonly SKILL_ROOT
KIT_SRC="${SKILL_ROOT}/assets/zephyr-container-infra"
readonly KIT_SRC

usage() {
    cat <<'USAGE'
Usage:
  zephyr_vendor_infra.sh install --target-repo <path> [options]
  zephyr_vendor_infra.sh update  --target-repo <path> [options]
  zephyr_vendor_infra.sh check   --target-repo <path>

Options:
  --target-repo <path>        Target repository root.
  --snapshot-image <image>    Standard snapshot image tag/repo (without digest).
  --snapshot-digest <sha256>  Digest for --snapshot-image.
  --snapshot-ref <ref>        Full digest-pinned standard image ref.
  --base-image-ref <ref>      Digest-pinned base image for derived-image builds.
  --runtime-image <tag>       Local/tagged derived runtime image (no digest required).
  --image-mode <mode>         standard|auto|derived (default: auto).
  --project-id <id>           Project ID in infra.yaml (default: target repo basename).
  --cache-root <path>         Cache root (default: /mnt/data_infra/zephyr_container_infra).
  --lease-mode <mode>         off|warn|enforce (default: warn).
  --cache-profile <profile>   shared|isolated|hybrid (default: shared).
  --force                     Allow install over existing kit.

Notes:
- install/update always write the vendored infra config in the target repo.
- image_ref is always digest-pinned.
- base_image_ref is digest-pinned for auto/derived modes.
USAGE
}

log() {
    echo "[zephyr-vendor] $*" >&2
}

err() {
    log "ERROR: $*"
    exit 1
}

read_yaml_value() {
    local file="$1"
    local key="$2"
    awk -F ':' -v want="${key}" '
        $0 ~ "^[[:space:]]*" want "[[:space:]]*:[[:space:]]*" {
            sub("^[[:space:]]*" want "[[:space:]]*:[[:space:]]*", "", $0)
            sub(/[[:space:]]+#.*/, "", $0)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", $0)
            gsub(/^"|"$/, "", $0)
            gsub(/^\047|\047$/, "", $0)
            print $0
            exit
        }
    ' "${file}"
}

require_digest() {
    local image_ref="$1"
    local label="${2:-image_ref}"
    [[ -n "${image_ref}" ]] || err "${label} is empty"
    [[ "${image_ref}" == *@sha256:* ]] || err "${label} must include @sha256: digest: ${image_ref}"
    local digest
    digest="${image_ref##*@sha256:}"
    [[ "${digest}" =~ ^[a-f0-9]{64}$ ]] || err "${label} digest must be 64 lowercase hex chars: ${digest}"
}

require_mode() {
    local image_mode="$1"
    case "${image_mode}" in
        standard|auto|derived)
            ;;
        *)
            err "image_mode must be one of standard|auto|derived (got '${image_mode}')"
            ;;
    esac
}

validate_mode_fields() {
    local image_mode="$1"
    local image_ref="$2"
    local base_image_ref="$3"
    local runtime_image="$4"

    require_mode "${image_mode}"
    require_digest "${image_ref}" "image_ref"

    if [[ -n "${base_image_ref}" ]]; then
        require_digest "${base_image_ref}" "base_image_ref"
    fi

    case "${image_mode}" in
        standard)
            ;;
        auto|derived)
            require_digest "${base_image_ref}" "base_image_ref"
            [[ -n "${runtime_image}" ]] || err "runtime_image must be set when image_mode=${image_mode}"
            ;;
    esac
}

copy_kit() {
    local target_kit="$1"
    mkdir -p "${target_kit}"
    if command -v rsync >/dev/null 2>&1; then
        rsync -a --delete "${KIT_SRC}/" "${target_kit}/"
    else
        rm -rf "${target_kit}"
        mkdir -p "${target_kit}"
        cp -a "${KIT_SRC}/." "${target_kit}/"
    fi
    chmod +x "${target_kit}/bin/repoctl" "${target_kit}/bin/jobctl"
    chmod +x "${target_kit}/container/launch_container.sh"
    chmod +x "${target_kit}/container/entrypoints/"*.sh
    chmod +x "${target_kit}/container/lib/"*.sh
    chmod +x "${target_kit}/container/verify_uv_layering.sh"
    chmod +x "${target_kit}/lib/"*.sh
    chmod +x "${target_kit}/build_repo_image.sh"
}

write_infra_yaml() {
    local infra_file="$1"
    local image_ref="$2"
    local base_image_ref="$3"
    local runtime_image="$4"
    local image_mode="$5"
    local project_id="$6"
    local cache_root="$7"
    local lease_mode="$8"
    local cache_profile="$9"

    cat > "${infra_file}" <<EOF_YAML
# Vendored Zephyr container infra configuration.
# Generated by skills/zephyr/scripts/zephyr_vendor_infra.sh.

image_ref: ${image_ref}
base_image_ref: ${base_image_ref}
runtime_image: ${runtime_image}
image_mode: ${image_mode}
project_id: ${project_id}
cache_root: ${cache_root}
lease_mode: ${lease_mode}
cache_profile: ${cache_profile}
entrypoint_default: default
extra_docker_args: ""
EOF_YAML
}

MODE="${1:-}"
if [[ -z "${MODE}" ]]; then
    usage
    exit 2
fi
if [[ "${MODE}" == "--help" || "${MODE}" == "-h" || "${MODE}" == "help" ]]; then
    usage
    exit 0
fi
shift || true

TARGET_REPO=""
SNAPSHOT_IMAGE=""
SNAPSHOT_DIGEST=""
SNAPSHOT_REF=""
BASE_IMAGE_REF_ARG=""
RUNTIME_IMAGE_ARG=""
IMAGE_MODE_ARG=""
PROJECT_ID=""
CACHE_ROOT=""
LEASE_MODE=""
CACHE_PROFILE=""
FORCE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --target-repo)
            TARGET_REPO="${2:-}"
            shift 2
            ;;
        --snapshot-image)
            SNAPSHOT_IMAGE="${2:-}"
            shift 2
            ;;
        --snapshot-digest)
            SNAPSHOT_DIGEST="${2:-}"
            shift 2
            ;;
        --snapshot-ref)
            SNAPSHOT_REF="${2:-}"
            shift 2
            ;;
        --base-image-ref)
            BASE_IMAGE_REF_ARG="${2:-}"
            shift 2
            ;;
        --runtime-image)
            RUNTIME_IMAGE_ARG="${2:-}"
            shift 2
            ;;
        --image-mode)
            IMAGE_MODE_ARG="${2:-}"
            shift 2
            ;;
        --project-id)
            PROJECT_ID="${2:-}"
            shift 2
            ;;
        --cache-root)
            CACHE_ROOT="${2:-}"
            shift 2
            ;;
        --lease-mode)
            LEASE_MODE="${2:-}"
            shift 2
            ;;
        --cache-profile)
            CACHE_PROFILE="${2:-}"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            err "Unknown argument: $1"
            ;;
    esac
done

[[ -d "${KIT_SRC}" ]] || err "Portable kit not found at ${KIT_SRC}"
[[ -f "${KIT_SRC}/container/launch_container.sh" ]] || err "Portable kit missing launch_container.sh"
[[ -f "${KIT_SRC}/build_repo_image.sh" ]] || err "Portable kit missing build_repo_image.sh"
[[ -f "${KIT_SRC}/Dockerfile.zephyr" ]] || err "Portable kit missing Dockerfile.zephyr"

[[ -n "${TARGET_REPO}" ]] || err "--target-repo is required"
TARGET_REPO="$(realpath "${TARGET_REPO}")"
[[ -d "${TARGET_REPO}" ]] || err "Target repo not found: ${TARGET_REPO}"
readonly KIT_DOT_DIR=".sygal""dry"
TARGET_KIT="${TARGET_REPO}/${KIT_DOT_DIR}/zephyr"
INFRA_FILE="${TARGET_KIT}/infra.yaml"

case "${MODE}" in
    install|update|check)
        ;;
    *)
        err "Unknown mode '${MODE}'. Use install|update|check."
        ;;
esac

if [[ "${MODE}" == "check" ]]; then
    [[ -d "${TARGET_KIT}" ]] || err "Missing kit: ${TARGET_KIT}"
    [[ -x "${TARGET_KIT}/bin/repoctl" ]] || err "Missing repoctl launcher"
    [[ -x "${TARGET_KIT}/bin/jobctl" ]] || err "Missing jobctl launcher"
    [[ -x "${TARGET_KIT}/build_repo_image.sh" ]] || err "Missing build_repo_image.sh"
    [[ -f "${TARGET_KIT}/Dockerfile.zephyr" ]] || err "Missing Dockerfile.zephyr"
    [[ -f "${INFRA_FILE}" ]] || err "Missing infra.yaml"

    image_ref="$(read_yaml_value "${INFRA_FILE}" image_ref || true)"
    base_image_ref="$(read_yaml_value "${INFRA_FILE}" base_image_ref || true)"
    runtime_image="$(read_yaml_value "${INFRA_FILE}" runtime_image || true)"
    image_mode="$(read_yaml_value "${INFRA_FILE}" image_mode || true)"

    if [[ -z "${image_mode}" ]]; then
        image_mode="auto"
    fi
    if [[ -z "${base_image_ref}" ]]; then
        base_image_ref="${image_ref}"
    fi
    if [[ -z "${runtime_image}" ]]; then
        runtime_image="$(basename "${TARGET_REPO}")/zephyr:dev"
    fi

    validate_mode_fields "${image_mode}" "${image_ref}" "${base_image_ref}" "${runtime_image}"

    log "check passed"
    log "kit=${TARGET_KIT}"
    log "image_ref=${image_ref}"
    log "base_image_ref=${base_image_ref}"
    log "runtime_image=${runtime_image}"
    log "image_mode=${image_mode}"
    exit 0
fi

if [[ "${MODE}" == "install" && -d "${TARGET_KIT}" && ${FORCE} -ne 1 ]]; then
    err "Target kit already exists at ${TARGET_KIT}. Use update or --force."
fi

existing_image_ref=""
existing_base_image_ref=""
existing_runtime_image=""
existing_image_mode=""
existing_project_id=""
existing_cache_root=""
existing_lease_mode=""
existing_cache_profile=""
if [[ -f "${INFRA_FILE}" ]]; then
    existing_image_ref="$(read_yaml_value "${INFRA_FILE}" image_ref || true)"
    existing_base_image_ref="$(read_yaml_value "${INFRA_FILE}" base_image_ref || true)"
    existing_runtime_image="$(read_yaml_value "${INFRA_FILE}" runtime_image || true)"
    existing_image_mode="$(read_yaml_value "${INFRA_FILE}" image_mode || true)"
    existing_project_id="$(read_yaml_value "${INFRA_FILE}" project_id || true)"
    existing_cache_root="$(read_yaml_value "${INFRA_FILE}" cache_root || true)"
    existing_lease_mode="$(read_yaml_value "${INFRA_FILE}" lease_mode || true)"
    existing_cache_profile="$(read_yaml_value "${INFRA_FILE}" cache_profile || true)"
fi

if [[ -n "${SNAPSHOT_REF}" ]]; then
    image_ref="${SNAPSHOT_REF}"
else
    if [[ -n "${SNAPSHOT_IMAGE}" || -n "${SNAPSHOT_DIGEST}" ]]; then
        [[ -n "${SNAPSHOT_IMAGE}" ]] || err "--snapshot-image is required when --snapshot-digest is used"
        [[ -n "${SNAPSHOT_DIGEST}" ]] || err "--snapshot-digest is required when --snapshot-image is used"
        image_ref="${SNAPSHOT_IMAGE}@sha256:${SNAPSHOT_DIGEST}"
    else
        image_ref="${existing_image_ref}"
    fi
fi
[[ -n "${image_ref}" ]] || err "Snapshot ref missing. Provide --snapshot-ref or --snapshot-image + --snapshot-digest."

if [[ -n "${BASE_IMAGE_REF_ARG}" ]]; then
    base_image_ref="${BASE_IMAGE_REF_ARG}"
elif [[ -n "${existing_base_image_ref}" ]]; then
    base_image_ref="${existing_base_image_ref}"
else
    base_image_ref="${image_ref}"
fi

if [[ -n "${IMAGE_MODE_ARG}" ]]; then
    image_mode="${IMAGE_MODE_ARG}"
elif [[ -n "${existing_image_mode}" ]]; then
    image_mode="${existing_image_mode}"
else
    image_mode="auto"
fi

if [[ -n "${RUNTIME_IMAGE_ARG}" ]]; then
    runtime_image="${RUNTIME_IMAGE_ARG}"
elif [[ -n "${existing_runtime_image}" ]]; then
    runtime_image="${existing_runtime_image}"
else
    runtime_image="$(basename "${TARGET_REPO}")/zephyr:dev"
fi

validate_mode_fields "${image_mode}" "${image_ref}" "${base_image_ref}" "${runtime_image}"

if [[ -z "${PROJECT_ID}" ]]; then
    PROJECT_ID="${existing_project_id:-$(basename "${TARGET_REPO}")}"
fi
if [[ -z "${CACHE_ROOT}" ]]; then
    CACHE_ROOT="${existing_cache_root:-/mnt/data_infra/zephyr_container_infra}"
fi
if [[ -z "${LEASE_MODE}" ]]; then
    LEASE_MODE="${existing_lease_mode:-warn}"
fi
if [[ -z "${CACHE_PROFILE}" ]]; then
    CACHE_PROFILE="${existing_cache_profile:-shared}"
fi

case "${LEASE_MODE}" in
    off|warn|enforce)
        ;;
    *)
        err "Invalid --lease-mode: ${LEASE_MODE} (off|warn|enforce)"
        ;;
esac
case "${CACHE_PROFILE}" in
    shared|isolated|hybrid)
        ;;
    *)
        err "Invalid --cache-profile: ${CACHE_PROFILE} (shared|isolated|hybrid)"
        ;;
esac

mkdir -p "${TARGET_REPO}/.sygaldry"
copy_kit "${TARGET_KIT}"
write_infra_yaml "${INFRA_FILE}" "${image_ref}" "${base_image_ref}" "${runtime_image}" "${image_mode}" "${PROJECT_ID}" "${CACHE_ROOT}" "${LEASE_MODE}" "${CACHE_PROFILE}"

log "${MODE} complete"
log "target=${TARGET_KIT}"
log "image_ref=${image_ref}"
log "base_image_ref=${base_image_ref}"
log "runtime_image=${runtime_image}"
log "image_mode=${image_mode}"
log "project_id=${PROJECT_ID}"
log "next: ${TARGET_KIT}/bin/repoctl config show"
