#!/usr/bin/env python3
"""Synchronize skills/LOCAL_SKILLS.md with local skill directories."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    script_path = Path(__file__).resolve()
    repo_root = script_path.parents[3]
    default_skills_dir = repo_root / "skills"
    default_output = default_skills_dir / "LOCAL_SKILLS.md"

    parser = argparse.ArgumentParser(
        description="Generate or verify skills/LOCAL_SKILLS.md from skills/*/SKILL.md."
    )
    parser.add_argument(
        "--skills-dir",
        type=Path,
        default=default_skills_dir,
        help=f"Skills directory (default: {default_skills_dir})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=default_output,
        help=f"Output markdown file (default: {default_output})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check for drift without writing changes (non-zero exit on mismatch).",
    )
    return parser.parse_args()


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1].strip()
    return value


def parse_skill_summary(skill_md: Path) -> str:
    text = skill_md.read_text(encoding="utf-8")
    description = ""

    if text.startswith("---\n"):
        end_marker = "\n---\n"
        end = text.find(end_marker, 4)
        if end != -1:
            frontmatter = text[4:end]
            match = re.search(r"^description:\s*(.+)$", frontmatter, flags=re.MULTILINE)
            if match:
                description = strip_quotes(match.group(1))
            text = text[end + len(end_marker) :]

    if description:
        return description

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        return line

    return "No description provided."


def rel_path(path: Path, base: Path) -> str:
    relative = path.resolve().relative_to(base.resolve())
    value = relative.as_posix()
    if path.is_dir() and not value.endswith("/"):
        return f"{value}/"
    return value


def collect_paths(skill_dir: Path, repo_root: Path) -> list[tuple[str, str]]:
    items: list[tuple[str, str]] = [
        ("Skill root", rel_path(skill_dir, repo_root)),
        ("SKILL.md", rel_path(skill_dir / "SKILL.md", repo_root)),
    ]

    optional_items: list[tuple[str, Path]] = [
        ("Validation", skill_dir / "VALIDATION.md"),
        ("Scripts", skill_dir / "scripts"),
        ("References", skill_dir / "references"),
        ("Assets", skill_dir / "assets"),
        ("Environment definitions", skill_dir / "envs"),
        ("Portable kit", skill_dir / "portable"),
        ("Agent metadata", skill_dir / "agents" / "openai.yaml"),
    ]

    for label, path in optional_items:
        if path.exists():
            items.append((label, rel_path(path, repo_root)))

    return items


def build_markdown(skills_dir: Path, output_path: Path) -> str:
    repo_root = output_path.resolve().parents[1]
    skill_dirs = sorted(
        [
            child
            for child in skills_dir.iterdir()
            if child.is_dir() and (child / "SKILL.md").is_file()
        ],
        key=lambda p: p.name,
    )

    lines = [
        "# Local Skills",
        "",
        "This file is generated by `skills/local-skills-sync/scripts/sync_local_skills.py`.",
        "Do not edit manually; rerun the sync script.",
        "",
        "This repo contains **repo-scoped** skills under `skills/` for validation before global install.",
        "",
    ]

    for index, skill_dir in enumerate(skill_dirs):
        skill_name = skill_dir.name
        summary = parse_skill_summary(skill_dir / "SKILL.md")
        lines.append(f"## {skill_name} (local only)")
        lines.append("")
        lines.append(summary)
        lines.append("")
        lines.append("Paths:")
        for label, path in collect_paths(skill_dir, repo_root):
            lines.append(f"- {label}: `{path}`")
        lines.append("")
        lines.append(
            "Do not install into `$CODEX_HOME/skills` until validation is complete."
        )
        if index != len(skill_dirs) - 1:
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def check_only(content: str, output_path: Path) -> int:
    if not output_path.exists():
        print(f"ERROR: Missing output file: {output_path}", file=sys.stderr)
        return 1

    current = output_path.read_text(encoding="utf-8")
    if current == content:
        print(f"OK: {output_path} is in sync.")
        return 0

    print(f"DRIFT: {output_path} is out of sync.", file=sys.stderr)
    diff = difflib.unified_diff(
        current.splitlines(),
        content.splitlines(),
        fromfile=f"{output_path} (current)",
        tofile=f"{output_path} (expected)",
        lineterm="",
    )
    for line in diff:
        print(line)
    return 1


def write_output(content: str, output_path: Path) -> int:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Updated {output_path}")
    return 0


def main() -> int:
    args = parse_args()
    skills_dir = args.skills_dir.resolve()
    output_path = args.output.resolve()

    if not skills_dir.exists() or not skills_dir.is_dir():
        print(f"ERROR: skills directory does not exist: {skills_dir}", file=sys.stderr)
        return 2

    content = build_markdown(skills_dir, output_path)
    if args.check:
        return check_only(content, output_path)
    return write_output(content, output_path)


if __name__ == "__main__":
    raise SystemExit(main())
